// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATimeline: typeof import('ant-design-vue/es')['Timeline']
    ATimelineItem: typeof import('ant-design-vue/es')['TimelineItem']
    Breezy: typeof import('./src/components/weather/breezy.vue')['default']
    Cloud: typeof import('./src/components/weather/cloud.vue')['default']
    Draw: typeof import('./src/components/Draw.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Night: typeof import('./src/components/weather/night.vue')['default']
    NodeList: typeof import('./src/components/NodeList.vue')['default']
    PreviewNode: typeof import('./src/components/PreviewNode.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Storm: typeof import('./src/components/weather/storm.vue')['default']
    Sunny: typeof import('./src/components/weather/sunny.vue')['default']
    TimeLine: typeof import('./src/components/TimeLine.vue')['default']
    Weather: typeof import('./src/components/weather.vue')['default']
    Whether: typeof import('./src/components/Whether.vue')['default']
  }
}

export { }
